from __future__ import annotations

import enum
from datetime import datetime
from typing import TYPE_CHECKING
from uuid import UUID, uuid4

from sqlalchemy import (
    BigInteger,
    CheckConstraint,
    DateTime,
    Enum,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    UniqueConstraint,
    func,
    text,
)
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.database import Base

if TYPE_CHECKING:
    from app.models.company import Company
    from app.models.user import User


class DocumentStatus(str, enum.Enum):
    QUEUED = "QUEUED"
    PROCESSING = "PROCESSING"
    READY = "READY"
    FAILED = "FAILED"
    DELETING = "DELETING"


class DocumentVisibility(str, enum.Enum):
    ALL_MEMBERS = "ALL_MEMBERS"
    ADMINS_ONLY = "ADMINS_ONLY"


class Document(Base):
    __tablename__ = "documents"

    __table_args__ = (
        CheckConstraint("file_size >= 0", name="ck_documents_file_size_nonnegative"),
        CheckConstraint(
            "page_count IS NULL OR page_count >= 0",
            name="ck_documents_page_count_nonnegative",
        ),
        CheckConstraint(
            "chunk_count IS NULL OR chunk_count >= 0",
            name="ck_documents_chunk_count_nonnegative",
        ),
        UniqueConstraint("company_id", "sha256", name="uq_documents_company_sha256"),
        Index("ix_documents_company_created", "company_id", "created_at"),
    )

    id: Mapped[UUID] = mapped_column(
        PG_UUID(as_uuid=True), primary_key=True, default=uuid4
    )

    company_id: Mapped[UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("companies.id", ondelete="CASCADE"),
        nullable=False,
    )

    uploaded_by_user_id: Mapped[UUID | None] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
    )

    # Original name from the user. Display only. Never use it as a file path.
    filename: Mapped[str] = mapped_column(String(255), nullable=False)

    # Generated by the server, e.g. f"{company_id}/{document_id}.pdf"
    storage_key: Mapped[str] = mapped_column(String(1024), nullable=False, unique=True)

    content_type: Mapped[str] = mapped_column(String(255), nullable=False)
    file_size: Mapped[int] = mapped_column(BigInteger, nullable=False)
    sha256: Mapped[str] = mapped_column(String(64), nullable=False)

    status: Mapped[DocumentStatus] = mapped_column(
        Enum(
            DocumentStatus,
            name="document_status",
            native_enum=False,
            create_constraint=True,
            validate_strings=True,
        ),
        nullable=False,
        default=DocumentStatus.QUEUED,
        server_default=text("'QUEUED'"),
    )

    visibility: Mapped[DocumentVisibility] = mapped_column(
        Enum(
            DocumentVisibility,
            name="document_visibility",
            native_enum=False,
            create_constraint=True,
            validate_strings=True,
        ),
        nullable=False,
        default=DocumentVisibility.ALL_MEMBERS,
        server_default=text("'ALL_MEMBERS'"),
    )

    page_count: Mapped[int | None] = mapped_column(Integer, nullable=True)
    chunk_count: Mapped[int | None] = mapped_column(Integer, nullable=True)

    # Short, safe message. Keep raw stack traces in server logs only.
    processing_error: Mapped[str | None] = mapped_column(Text, nullable=True)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )

    company: Mapped[Company] = relationship(back_populates="documents")
    uploaded_by: Mapped[User | None] = relationship(back_populates="uploaded_documents")